apiVersion: v1
kind: Service
metadata:
  name: front-app-service
  namespace: bdc105
  labels:
    app: front-app
spec:
  type: NodePort
  selector:
    app: front-app
  ports:
    - name: http
      protocol: TCP
      port: 3000          # Service 내부 포트
      targetPort: 3000    # Pod의 컨테이너 포트
      nodePort: 31051     # 외부 접근 포트 (30000-32767 범위)
  sessionAffinity: None

